name: KAMIS API test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run test
        env:
          KAMIS_API_KEY: ${{ secrets.KAMIS_API_KEY }}
        run: python kamis_test.py